### ISSUE TITLE
After contig selection is saved, automatically hide saved contigs from view.

### ISSUE THREAD

**Issue by samche42** [WiscEvan/Automappa#17]
I.e. after you have decided on your bin and saved the selection, those contigs disappear and cannot be placed into a different bin (Save the user from themselves here).

**Comment by WiscEvan** [comment]
This is already implemented if you keep the `hide MAG refinements` toggle to on, the contigs should hide after the selection... Albeit, for particularly large datasets, this may take some time. What we should probably do is add loading states for all of the graphs to display to the user that information is still updating before making more selections. This can be done by adding a [`dbc.Loading`](https://dash.plotly.com/dash-core-components/loading) component to the figure/table that we would want to display a loading state.

**Comment by WiscEvan** [comment]
I've now added the loading components 👍
