### ISSUE TITLE
Replace default page tab icon

### ISSUE THREAD

**Issue by WiscEvan** [WiscEvan/Automappa#21]
To replace the default page tab icon, we simply need to add a `favicon.ico` file to `/assets/favicon.ico`.

Happy to receive any suggestions on what icon design we could use.

For starters, we could use an `A`? Maybe the same A that is in the Autometa logo animation?

https://user-images.githubusercontent.com/25933122/145425205-aa093d40-b359-452b-921a-da4465c6da67.mp4

There may be some helpful inspiration in https://github.com/KwanLab/Autometa/issues/75

**Comment by WiscEvan** [comment]
# Some other suggestions by @samche42

-------

![image](https://user-images.githubusercontent.com/25933122/148104990-f38e376c-5386-4e99-9b5c-6f8522348b0b.png)


## Logo A

![image (1)](https://user-images.githubusercontent.com/25933122/148105138-3ff1b0dd-6cce-4925-b47d-2a34774381d3.png)

## Logo B

![image (2)](https://user-images.githubusercontent.com/25933122/148105333-7d60c22d-87cb-4152-ae2a-b5c02a897112.png)

## Logo C & Logo D

**Comment by samche42** [comment]
Logo E - Could also be re-purposed for Autometa?

![image](https://user-images.githubusercontent.com/60663840/148129858-2ae6bd81-1f4b-450b-998d-d03069b6a5d5.png)

**Comment by samche42** [comment]
Logo F - a reimagining of logo A
![image](https://user-images.githubusercontent.com/60663840/148134342-fc5e792b-8c57-4b41-bc09-86780190099e.png)

**Comment by WiscEvan** [comment]
By @samche42

![image (3)](https://user-images.githubusercontent.com/25933122/148137738-66b9e9c2-d106-4ef5-a8d1-146ea3c63b16.png)

## Logo G

**Comment by samche42** [comment]
Logo H
![image](https://user-images.githubusercontent.com/60663840/148138377-4a5988ac-3822-416d-9fd7-f994e52d92c5.png)
