### ISSUE TITLE
An approach to editing/removing/adding "vestigial" contigs from refined bins

### ISSUE THREAD

**Issue by WiscEvan** [WiscEvan/Automappa#29]
@samche42 Ideas welcome....

- Move contigs from bins that were not selected into unclustered

**Comment by samche42** [comment]
If all bins are refined (suggested) then you could simply move anything still in a bin*.fasta file to unclustered. 

However, if a user chooses to only edit a handful of bins and ultimately ends with a mix of bins and refinements, this could be more tricky to address. Perhaps a workaround would be if any bins are less than 20% complete they get moved into the unclustered fasta file?

**Comment by WiscEvan** [comment]
With #39 if an initial MAG is split by a user's manual refinement, any of the contigs that were in the initial MAG but not included in the user's refinement will be recognized as "outdated" (i.e. unclustered) and thus not be considered when downloading refinements or at the MAG summary page. I believe this is the intended and requested behavior, so am closing for now. If this is not what was requested, feel free to re-open. 🤠
