### ISSUE TITLE
problem installing

### ISSUE THREAD

**Issue by imonteroo** [WiscEvan/Automappa#36]
I installed automappa and autometa. When I run test files y received this error

```
Traceback (most recent call last):
  File "/media/microviable/d/miniconda/Automappa/bin/automappa", line 7, in <module>
    from automappa.__main__ import main
  File "/media/microviable/d/miniconda/Automappa/lib/python3.9/site-packages/automappa/__main__.py", line 4, in <module>
    from automappa import index
  File "/media/microviable/d/miniconda/Automappa/lib/python3.9/site-packages/automappa/index.py", line 20, in <module>
    from automappa.apps import mag_refinement, mag_summary
  File "/media/microviable/d/miniconda/Automappa/lib/python3.9/site-packages/automappa/apps/mag_refinement.py", line 12, in <module>
    from dash_extensions import Download
ImportError: cannot import name 'Download' from 'dash_extensions' (/media/microviable/d/miniconda/Automappa/lib/python3.9/site-packages/dash_extensions/__init__.py)
```

**Comment by imonteroo** [comment]
after install dash-extensions with poetri the error changed

`Traceback (most recent call last):
  File "/media/microviable/d/miniconda/autometa/bin/automappa", line 7, in <module>
    from automappa.__main__ import main
  File "/media/microviable/d/miniconda/autometa/lib/python3.9/site-packages/automappa/__main__.py", line 4, in <module>
    from automappa import index
  File "/media/microviable/d/miniconda/autometa/lib/python3.9/site-packages/automappa/index.py", line 20, in <module>
    from automappa.apps import mag_refinement, mag_summary
  File "/media/microviable/d/miniconda/autometa/lib/python3.9/site-packages/automappa/apps/mag_refinement.py", line 12, in <module>
    from dash_extensions import Download
  File "/media/microviable/d/dash-extensions/dash_extensions/__init__.py", line 10, in <module>
    from ._imports_ import *
  File "/media/microviable/d/dash-extensions/dash_extensions/_imports_.py", line 1, in <module>
    from .BeforeAfter import BeforeAfter
ModuleNotFoundError: No module named 'dash_extensions.BeforeAfter'
`

**Comment by WiscEvan** [comment]
Hello @imonteroo, thank you for reaching out. I'll double check the install and update you. I think I may need to pin some dependencies to resolve this.

**Comment by WiscEvan** [comment]
Hello @imonteroo, to more quickly troubleshoot this, would you please provide your installation and runtime commands and their respective output, if any? 


## Commands used

```bash
# install command:
>cmd:
# run command:
>cmd:
```

Automappa version: 


## Environment

```bash
# copy/paste output from 
mamba env export --no-builds -n automappa
```


Thanks!

**Comment by imonteroo** [comment]
*Commands used*

*# install command:*$  mamba install -c bioconda automappa


*# run command:*$ automappa

Traceback (most recent call last):
  File "/media/microviable/d/miniconda/autometa/bin/automappa", line 7, in
<module>
    from automappa.__main__ import main
  File
"/media/microviable/d/miniconda/autometa/lib/python3.9/site-packages/automappa/__main__.py",
line 4, in <module>
    from automappa import index
  File
"/media/microviable/d/miniconda/autometa/lib/python3.9/site-packages/automappa/index.py",
line 20, in <module>
    from automappa.apps import mag_refinement, mag_summary
  File
"/media/microviable/d/miniconda/autometa/lib/python3.9/site-packages/automappa/apps/mag_refinement.py",
line 12, in <module>
    from dash_extensions import Download
ImportError: cannot import name 'Download' from 'dash_extensions'
(/media/microviable/d/miniconda/autometa/lib/python3.9/site-packages/dash_extensions/__init__.py)


*Automappa version:*
conda list
# packages in environment at /media/microviable/d/miniconda/autometa:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
asttokens                 2.0.8              pyhd8ed1ab_0    conda-forge
attrs                     22.1.0             pyh71513ae_1    conda-forge

*automappa                 2.1.0              pyh5e36f6f_0    bioconda*autometa
                 2.1.0              pyh5e36f6f_0    bioconda
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.11.1             pyha770c72_0    conda-forge
bedtools                  2.30.0               h468198e_3    bioconda
biopython                 1.79             py39hb9d737c_3    conda-forge
boost-cpp                 1.74.0               h75c5d50_8    conda-forge
bowtie2                   2.4.5            py39h3321a2d_4    bioconda
brotli                    1.0.9                h166bdaf_8    conda-forge
brotli-bin                1.0.9                h166bdaf_8    conda-forge
brotli-python             1.0.9            py39h5a03fae_8    conda-forge
brotlipy                  0.7.0           py39hb9d737c_1005    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.9.24            ha878542_0    conda-forge
cachecontrol              0.12.12            pyhd8ed1ab_1    conda-forge
cachelib                  0.9.0              pyhd8ed1ab_0    conda-forge
certifi                   2022.9.24          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py39he91dace_2    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
click                     8.1.3           unix_pyhd8ed1ab_2    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
conda                     22.9.0           py39hf3d152e_1    conda-forge
conda-package-handling    1.9.0            py39hb9d737c_1    conda-forge
contourpy                 1.0.5            py39hf939315_1    conda-forge
cryptography              38.0.2           py39hd97740a_2    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cython                    0.29.32          py39h5a03fae_1    conda-forge
dash                      2.6.2              pyhd8ed1ab_0    conda-forge
dash-bootstrap-components 1.2.1              pyhd8ed1ab_0    conda-forge
dash-core-components      2.0.0                    pypi_0    pypi
dash-daq                  0.5.0              pyh9f0ad1d_1    conda-forge
dash-down                 0.1.1                    pypi_0    pypi
dash-extensions           0.1.6              pyhd8ed1ab_0    conda-forge
dash-html-components      2.0.0                    pypi_0    pypi
dash-iconify              0.1.2                    pypi_0    pypi
dash-leaflet              0.1.23                   pypi_0    pypi
dash-mantine-components   0.10.2                   pypi_0    pypi
dash-table                5.0.0                    pypi_0    pypi
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
diamond                   2.0.15               hb97b32f_1    bioconda
editorconfig              0.12.3             pyhd8ed1ab_0    conda-forge
exceptiongroup            1.0.0              pyhd8ed1ab_0    conda-forge
executing                 1.1.1              pyhd8ed1ab_0    conda-forge
filelock                  3.8.0              pyhd8ed1ab_0    conda-forge
flask                     2.1.2                    pypi_0    pypi
flask-caching             2.0.0                    pypi_0    pypi
flask-compress            1.13               pyhd8ed1ab_0    conda-forge
fonttools                 4.38.0           py39hb9d737c_1    conda-forge
freetype                  2.12.1               hca18f0e_0    conda-forge
gdown                     4.5.3              pyhd8ed1ab_0    conda-forge
geobuf                    1.1.1                    pypi_0    pypi
hdbscan                   0.8.28           py39hce5d2b2_1    conda-forge
hdmedians                 0.14.2           py39h2ae25f5_3    conda-forge
hmmer                     3.3.2                h87f3376_2    bioconda
htslib                    1.11                 hd3b49d5_2    bioconda
icu                       70.1                 h27087fc_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        5.0.0              pyha770c72_1    conda-forge
iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
ipython                   8.5.0              pyh41d4057_1    conda-forge
itsdangerous              2.1.2              pyhd8ed1ab_0    conda-forge
jbig                      2.1               h7f98852_2003    conda-forge
jedi                      0.18.1             pyhd8ed1ab_2    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
joblib                    1.2.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h166bdaf_2    conda-forge
jsbeautifier              1.14.7                   pypi_0    pypi
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.4            py39hf939315_1    conda-forge
krb5                      1.19.3               h3790be6_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.39                 hc81fddc_0    conda-forge
lerc                      2.2.1                h9c3ff4c_0    conda-forge
libarchive                3.5.2                hb890918_3    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h166bdaf_8    conda-forge
libbrotlidec              1.0.9                h166bdaf_8    conda-forge
libbrotlienc              1.0.9                h166bdaf_8    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libcurl                   7.86.0               h7bff187_0    conda-forge
libdeflate                1.7                  h7f98852_5    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgfortran-ng            12.2.0              h69a702a_19    conda-forge
libgfortran5              12.2.0              h337968e_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libllvm11                 11.1.0               he0ac6c6_5    conda-forge
libmamba                  0.27.0               h0dd8ff0_0    conda-forge
libmambapy                0.27.0           py39hd55135b_0    conda-forge
libnghttp2                1.47.0               hdcd2b5c_1    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
libpng                    1.6.38               h753d276_0    conda-forge
libsolv                   0.7.22               h6239696_0    conda-forge
libssh2                   1.10.0               haa6b8db_3    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libtiff                   4.3.0                hf544144_1    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp-base              1.2.4                h166bdaf_0    conda-forge
libxml2                   2.10.3               h7463322_0    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
llvmlite                  0.39.1           py39h7d9a04d_1    conda-forge
lockfile                  0.12.2                     py_1    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
mamba                     0.27.0           py39hfa8f2c8_0    conda-forge
markupsafe                2.1.1            py39hb9d737c_2    conda-forge
matplotlib-base           3.6.1            py39hf9fd14e_1    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
megahit                   1.2.9                h2e03b76_1    bioconda
mistune                   2.0.4                    pypi_0    pypi
more-itertools            8.14.0                   pypi_0    pypi
msgpack-python            1.0.4            py39hf939315_1    conda-forge
munkres                   1.0.7                      py_1    bioconda
natsort                   8.2.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
numba                     0.56.3           py39h61ddf18_0    conda-forge
numpy                     1.23.4           py39h3d75532_1    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.5.0                h7d73246_0    conda-forge
openssl                   1.1.1s               h166bdaf_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.5.1            py39h4661b88_1    conda-forge
parallel                  20160622                      1    bioconda
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
perl                      5.32.1          2_h7f98852_perl5    conda-forge
perl-threaded             5.32.1               hdfd78af_1    bioconda
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.4.0            py39ha612740_0    conda-forge
pip                       22.3               pyhd8ed1ab_0    conda-forge
plotly                    5.10.0             pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0            py39hf3d152e_4    conda-forge
popt                      1.16                          1    bioconda
prodigal                  2.6.3                hec16e2b_4    bioconda
prompt-toolkit            3.0.31             pyha770c72_0    conda-forge
protobuf                  4.21.9                   pypi_0    pypi
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.4            py39hb9d737c_1    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.13.0             pyhd8ed1ab_0    conda-forge
pynndescent               0.5.7              pyh6c4a22f_0    conda-forge
pyopenssl                 22.1.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pytest                    7.2.0            py39hf3d152e_1    conda-forge
python                    3.9.9           h62f1059_0_cpython    conda-forge
python-annoy              1.17.0           py39h5a03fae_4    conda-forge
python-box                6.0.2                    pypi_0    pypi
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytz                      2022.5             pyhd8ed1ab_0    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
reproc                    14.2.3               h7f98852_0    conda-forge
reproc-cpp                14.2.3               h9c3ff4c_0    conda-forge
requests                  2.28.1             pyhd8ed1ab_1    conda-forge
rsync                     3.2.7                h220164a_0    conda-forge
ruamel_yaml               0.15.80         py39hb9d737c_1008    conda-forge
samtools                  1.11                 h6270b1f_0    bioconda
scikit-bio                0.5.6            py39h16ac069_4    conda-forge
scikit-learn              0.24.0           py39h4dfa638_0    conda-forge
scipy                     1.9.3            py39hddc5342_1    conda-forge
setuptools                65.5.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
sqlite                    3.37.0               h9cd32fc_0    conda-forge
stack_data                0.5.1              pyhd8ed1ab_0    conda-forge
tbb                       2021.6.0             h924138e_1    conda-forge
tenacity                  8.1.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tqdm                      4.64.1             pyhd8ed1ab_0    conda-forge
traitlets                 5.5.0              pyhd8ed1ab_0    conda-forge
trimap                    1.0.15             pyh5e36f6f_0    bioconda
tsne                      0.3.1            py39hcb82e07_3    conda-forge
tzdata                    2022e                h191b570_0    conda-forge
umap-learn                0.5.3            py39hf3d152e_0    conda-forge
unicodedata2              14.0.0           py39hb9d737c_2    conda-forge
urllib3                   1.26.11            pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
werkzeug                  2.2.2              pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xxhash                    0.8.0                h7f98852_3    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
yaml-cpp                  0.7.0                h27087fc_2    conda-forge
zipp                      3.10.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h166bdaf_4    conda-forge
zstd                      1.5.2                h6239696_4
 conda-forgeEnvironment

*Environment*


*# copy/paste output from*mamba env export --no-builds -n automappa

xport --no-builds -n automappa
name: automappa
channels:
  - bioconda
  - biobakery
  - conda-forge
  - defaults
  - plotly
  - ursky
  - cruizperez
prefix: /media/microviable/d/miniconda/automappa

Ignacio Montero Ordóñez, PhD
Computational Biologist
Microviable Therapeutics SL
Edificio Severo Ochoa, planta -1
C/ Fernando Bonguera s/n
33005 Oviedo
www.microviable.com

Este mensaje se dirige exclusivamente a su destinatario y puede contener
información privilegiada o confidencial. Si no es Ud. el destinatario
indicado, queda notificado de que la utilización, divulgación y/o copia sin
autorización está prohibida en virtud de la legislación vigente.
This message is exclusively for the use of the addressee and it may contain
confidential or legally privileged information. Any use, copying or
dissemination of this information by anyone other than the intended
recipient is prohibited. If you have received this communication in error,
please contact the sender and delete it from your system.

**Comment by WiscEvan** [comment]
Hi Ignacio, dash-extensions has a number of new releases that I have started to work with on the `develop` branch (`automappa` fullly-featured service).

To fix the dependency issue from `mamba install -c bioconda automappa` you will need to downgrade `dash-extensions` to `0.0.71`


## Dependency fix

### If `automappa` is env name

You can do this in your automappa environment with:

 ```bash
mamba update -n automappa "dash-extensions=0.0.71"
```

or conda equivalent:

```bash
conda update -n automappa "dash-extensions=0.0.71"
```

### Using your `autometa` env name

```bash
conda update -n autometa "dash-extensions=0.0.71"
```

**Comment by imonteroo** [comment]
The error disappeared.

Thank you

Ignacio Montero Ordóñez, PhD
Computational Biologist
Microviable Therapeutics SL
Edificio Severo Ochoa, planta -1
C/ Fernando Bonguera s/n
33005 Oviedo
www.microviable.com

Este mensaje se dirige exclusivamente a su destinatario y puede contener
información privilegiada o confidencial. Si no es Ud. el destinatario
indicado, queda notificado de que la utilización, divulgación y/o copia sin
autorización está prohibida en virtud de la legislación vigente.
This message is exclusively for the use of the addressee and it may contain
confidential or legally privileged information. Any use, copying or
dissemination of this information by anyone other than the intended
recipient is prohibited. If you have received this communication in error,
please contact the sender and delete it from your system.
